### ISSUE TITLE
New Enemy Ideas

### ISSUE THREAD

**Issue by NimNimR4r** [rennieb1/HighwynnGame#2]
**Projectiles** 
* Snake (standard enemy) - shoots venom at player 
* Spider - shoots cobwebs at player
* Porcupine - shoots spines at player, this could be triggered by player jumping onto a log that it may be in/on
* Bat - drops rancid fruit on player 

***
**Mine**
* Porcupine - "      " 

***
**Impale**
* Stalk - impales the player with its beak, this is your larger than average stalk, could be a mini boss if challenging enough (think of that massive spider in Limbo) 

***
**Swoop**
* Corvid - deals damage by swooping and hitting player

**Comment by rennieb1** [comment]
Stork was made and implemented
The spider was made and implemented
